stages:
  - build
  - test

build-job:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build

test-job:
  stage: test
  image: node:18
  script:
    - npm install
    - npm run test